name: Publish PyPI Packages
on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build:
    name: Build Distributions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.x"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          build packaging setuptools wheel

      # TODO: upload to PyPI and PyPI Testing
      - name: Build Distribution
        run: |
          python -m build